public class Constants {
    public static final Map<String, String> TIPO_CONTRIBUYENTE = new Map<String,String>{
        'Consumidor Final' => '1',
        'Exento	' => '2',
        'Exportación' => '3',
        'Importación' => '6',
        'Monotributo' => '4',
        'No Informada' => '7',
        'Otros' => '9',
        'Régimen Simplificado' => '10',
        'Responsable Inscripto' => '5',
        'Responsable No Inscripto' => '8'
    };
        public static final Map<String, String> NUMERO_FACTURA = new Map<String,String>{
        	'1'=>'A',
            '2'=>'B',
            '4'=>'E'
    };
}